name: rag_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch-cpu
  - torchvision
  - psycopg2-binary
  - pip
  - pip:
    - ipykernel
    - ipywidgets
    - transformers
    - sentence_transformers
    - ollama
    - nltk
    - sqlalchemy 
    - pgvector
    - docling  